### ISSUE TITLE
Consider adding a Donation Button instead of large QR on every page.

### ISSUE THREAD

**Issue by nvk** [phezco/phez#1]
Cool site/idea!

Check out this button http://blog.coinkite.com/post/122796324311, all you need is to create a wallet there (multisig, or even forward the funds out), but it creates a proper bip32 HD checkout. 

Adding the link to the template is as easy as adding a link or embedding an image.

**Comment by phezco** [comment]
Thanks for the feedback. I'll definitely consider it.

Perhaps both?  (a QR code and donate button)

**Comment by nvk** [comment]
The button would take you to a page with a QR, I get the motivation but register users will see it too much.

**Comment by wadestuart** [comment]
I guess I am missing the user experience need to show QR at all?  Kind of equivalent to having a wav file "say" a URL for you isn't it?  I mean links do actually work on websites, it is not like a user is reading this on a printout.

**Comment by phezco** [comment]
@wadestuart - you make a good point. I guess the idea was that if someone wants to whip out their phone and scan the QR code they could more easily donate.

But I like the idea of a donate button, and CoinKite has some nice looking ones.

I've added a Figaro environment variable (config/application.yml) called 'donate_code' that can hold the embeddable html.

CoinKite button live now at:
http://phez.co/

Appears to be working, too.

**Comment by nvk** [comment]
:+1:
