### ISSUE TITLE
Forum and Discussion

### ISSUE THREAD

**Issue by askl56** [phezco/phez#12]
Before I can meaningfully put time into contributing to this project, would it be possible to have a chat with people if there is a Slack/forum to talk about aims, objectives and the plan? Or did I miss somewhere where that was listed?

**Comment by phezco** [comment]
Great question! I've been thinking about creating a Slack channel for this.

It's now live at: http://phez.slack.com/

I think I need your email to send you an invite.

**Comment by askl56** [comment]
amscott@openmailbox.org
