### ISSUE TITLE
Thoughts on Pagekeeper thumbnails?

### ISSUE THREAD

**Issue by phezco** [phezco/phez#4]
I've pushed an update that allows a Phez site operator to enable thumbnails via the Pagekeeper API.

What do you guys think of the look & feel of these thumbs?

I'm not too hot on:
- the loading animated gif when they haven't indexed the page yet
- they don't crop the thumbnails very well for extra wide or long photos

It'd also be a big undertaking to roll an in-house solution, so I'm not sure what to do next.

**Comment by Diope** [comment]
I think for the present time they're completely fine.

**Comment by phezco** [comment]
Sounds good. Closing this issue for now. Maybe down the road we'll implement an in-house solution that pull down remote images and resizes them into better thumbnails.
