### ISSUE TITLE
Review and test Authenticated API (uses doorkeeper + oauth2 gems)

### ISSUE THREAD

**Issue by phezco** [phezco/phez#8]
Hey all.

I'm looking for someone to review and test a new in-progress API implementation for Phez that requires authentication. It's using the doorkeeper + oauth2 gems.

You can review/checkout the branch at:
https://github.com/phezco/phez/tree/api

Here's some ruby code that uses the API:
https://gist.github.com/phezco/ff4d23e162c98b7c88bf

I got that part working locally. It spits out the username of the authenticated user, etc.

However I'd love to have some more eyes on this before I push it live. Especially testing with other OAuth2 client applications.

Note: I've created a bounty for this issue on Bountysource:
https://www.bountysource.com/issues/24557244-review-and-test-authenticated-api-uses-doorkeeper-oauth2-gems

**Comment by krekoten** [comment]
It seems like you need to close this issue and than Bountysource will allow me to claim bounty.

**Comment by phezco** [comment]
@krekoten helped me review and test the doorkeeper API implementation. thanks!
